services:

    pignus.authenticator.abstract:
        abstract: true
        class: Pignus\Authenticator\AbstractAuthenticator
        public: false
        arguments:
            - '@router'
            - '@session'
            - '@security.encoder_factory'
            - '@security.firewall.map'

    pignus.provider.abstract:
        abstract: true
        class: Pignus\Provider\GenericUserProvider
        public: false
